### ISSUE TITLE
Accessibility - General - TalkBack Reads the Header then the Footer and then the Main Content Section of the Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-Android#12]
TalkBack reads the items in the header section of the application and then reads those in the footer followed by the main content section for all the screens I have tested so far. I would expect TalkBack to read from top to bottom and not the way it reads currently, so that would be the header section, then the main content, and finally the footer section.

**Comment by greg-gruse** [comment]
This is a duplicate of https://github.com/USDepartmentofLabor/OCIO-DOLSafety-Android/issues/11

**Comment by jfc3-dol** [comment]
Closing issue as duplicate.
