### ISSUE TITLE
Accessibility - Main Screen - TalkBack Focus Stays on "All Incidents" Button in Footer

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-Android#30]
Once the user taps on the “All Incidents” link/tab in the footer section of the screen, I would expect to be focused at the top of the screen instead of staying at the bottom of the screen on the "All Incidents" link/tab. I believe that this happens on other screens too, where it does not focus on the top of the screen.

**Comment by greg-gruse** [comment]
This is a duplicate of issue https://github.com/USDepartmentofLabor/OCIO-DOLSafety-Android/issues/15

**Comment by jfc3-dol** [comment]
Closing issue as a duplicate.
