### ISSUE TITLE
Accessibility - Main Screen - TalkBack Tells  User There Were Over 215+ Incidents

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-Android#31]
Why are all the incidents listed and not broken up into sections/are paginated? It’s a bit confusing when TalkBack say there were 215+ items. Most people aren’t expecting all the items in one list but maybe 10, 25, 50, or even 100. If the items could be paginated then they could listen to the first set of incidents and the next if they use the next button.

**Comment by greg-gruse** [comment]
This is a duplicate of issue https://github.com/USDepartmentofLabor/OCIO-DOLSafety-Android/issues/13

**Comment by jfc3-dol** [comment]
Okay, will close this issue and leave #13 open then.
