### ISSUE TITLE
Fucntional - Main Screen - Miss Labeled Screen Name

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-Android#33]
Why is this screen called the “All Incidents” in the footer but its “Main” on the screen? Same applies for the footer section where it says “My Incidents” and then "Main" in the header section.

**Comment by greg-gruse** [comment]
This is a duplicate of issue 9

**Comment by jfc3-dol** [comment]
Closing issue as a duplicate.
