### ISSUE TITLE
Functional - Review Incident Screen - Incident Missing "Submitted By" Name

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-Android#47]
Why for Incident #2 is there no name for "Submitted By"? My guess is it was submitted while starting building the application so required fields were not enforced yet or it was an anonymous incident which I thought gets "Anonymous" as the name.

**Comment by greg-gruse** [comment]
This was an early bug fixed some time ago, the data was not properly updated, all of this data will be deleted before the release so this is not an issue others will see.

**Comment by jfc3-dol** [comment]
That's what I expected was the case and wanted to notify you if it was an actual problem.

So I'm going to close the issue.
