### ISSUE TITLE
Accessibility - General - Why User Not notified They Will be Logged Out

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-Android#68]
The SafetyNET application should warn the user that they are getting logged out and that they need to log back in instead of forcing them back to the application's main screen especially if they have been using the application the whole time. Also, by forcing the user off the application, they will most likely lose all the information they were typing in their incident or profile. For some people, it takes them longer to enter information, or they're really detailed with their issue. Does the application have to log them off for any given reason? I could see doing it after a half a day or more, but otherwise, people might start their entry in the morning before a meeting and not get back to it for a few hours and now all that information will be lost.

**Comment by greg-gruse** [comment]
This is a duplicate of issue #51

**Comment by jfc3-dol** [comment]
Okay, I will close this issue.
